gen::add_generator "Ada" gen_ada::generate

namespace eval gen_ada {

# Autogenerated with DRAKON Editor 1.33

proc assign { variable value } {
    return ""
}

proc block_close { output depth } {
    return ""
}

proc check { keywords args } {
    foreach arg $args {
        upvar 1 $arg keyword
        if {[ contains $keywords $arg ]} {
            set keyword 1
        } else {
            set keyword 0
        }
    }
}

proc classify_keywords { keywords name } {
    set errors {}
    check $keywords \
    	abstract inline protected tagged
    set access [ find_keywords \
     $keywords { private public } ]
    set _sw2540000_ [ llength $access ]
    if {$_sw2540000_ == 0} {
        set access "static"
    } else {
        if {$_sw2540000_ == 1} {
            
        } else {
            lappend errors \
             "$name: inconsistent access: $access"
        }
    }
    set subtype [ find_keywords $keywords \
      { type } ]
    set _sw4470000_ [ llength $subtype ]
    if {$_sw4470000_ == 0} {
        set subtype "subprogram"
    } else {
        if {$_sw4470000_ == 1} {
            
        } else {
            lappend errors \
             "$name: inconsistent type: $subtype"
        }
    }
    if {($inline) && ($abstract)} {
        lappend errors \
        "$name: both inline and abstract is not allowed"
    }
    if {($subtype == "subprogram") || ($subtype == "type")} {
        
    }
    array set props {}
    set props(abstract) $abstract
    set props(inline) $inline
    set props(protected) $protected
    set props(tagged) $tagged
    set props(access) $access
    set props(subtype) $subtype
    set proplist [ array get props ]
    set error_message [ join $errors "\n" ]
    return [ list $error_message $proplist ]
}

proc comment { line } {
    return ""
}

proc compare { variable value } {
    return ""
}

proc create_tree { prefix tree } {
    lassign $tree \
    	id type header text children
    set lcase [ string tolower $text ]
    set basename [ string cat $prefix $lcase ]
    set bfile [ string cat $basename ".adb" ]
    close [ open $bfile a ]
    set sfile [ string cat $basename ".ads" ]
    close [ open $sfile a ]
    set prefix [ string cat $basename "-" ]
    foreach child $children {
        create_tree $prefix $child
    }
}

proc declare { type name value } {
    return ""
}

proc else_start { } {
    return ""
}

proc extract_return_type { text } {
    set skip [ string length "returns " ]
    set raw [ string range $text $skip end ]
    return [ string trim $raw ]
}

proc extract_signature { text name } {
    array set props { abstract 0 \
    	access public \
    	inline 0 \
    	subtype procedure \
    	tagged 0 }
    set error_message ""
    set parameters {}
    set type "subprogram"
    set returns ""
    set lines [ gen::separate_from_comments $text ]
    if {[ llength $lines ] == 0} {
        set returns ""
        if {$type == "subprogram"} {
            if {$returns == ""} {
                set props(subtype) "procedure"
            } else {
                set props(subtype) "function"
            }
        }
    } else {
        set first_line [ lindex $lines 0 ]
        set first [ lindex $first_line 0 ]
        set keywords { 
        	abstract \
        	inline \
        	public \
        	private \
        	protected \
        	tagged \
        	type }
        set found_keywords \
         [ find_keywords $first $keywords ]
        if {[ llength $found_keywords ] == 0} {
            set start_index 0
            set count [ llength $lines ]
            set last [ expr { $count - 1 } ]
            set i $start_index
            while { 1 } {
                if {$i < $count} {
                    
                } else {
                    break
                }
                set current [ lindex $lines $i ]
                set stripped [ lindex $current 0 ]
                if {[ string match "returns *" $stripped ]} {
                    if {$i == $last} {
                        set returns [ \
                        	extract_return_type $stripped ]
                    } else {
                        set error_message \
                        "$name: 'returns' can only be the last line."
                    }
                    break
                }
                lappend parameters $current
                incr i
            }
            if {$type == "subprogram"} {
                if {$returns == ""} {
                    set props(subtype) "procedure"
                } else {
                    set props(subtype) "function"
                }
            }
        } else {
            set start_index 1
            set alien_keywords \
             [ find_not_belonging $first $keywords ]
            if {[ llength $alien_keywords ] == 0} {
                lassign [ classify_keywords $found_keywords $name ] \
                	error_message prop_list
                if {$error_message == ""} {
                    array unset props
                    array set props $prop_list
                    set type $props(subtype)
                    set count [ llength $lines ]
                    set last [ expr { $count - 1 } ]
                    set i $start_index
                    while { 1 } {
                        if {$i < $count} {
                            
                        } else {
                            break
                        }
                        set current [ lindex $lines $i ]
                        set stripped [ lindex $current 0 ]
                        if {[ string match "returns *" $stripped ]} {
                            if {$i == $last} {
                                set returns [ \
                                	extract_return_type $stripped ]
                            } else {
                                set error_message \
                                "$name: 'returns' can only be the last line."
                            }
                            break
                        }
                        lappend parameters $current
                        incr i
                    }
                    if {$type == "subprogram"} {
                        if {$returns == ""} {
                            set props(subtype) "procedure"
                        } else {
                            set props(subtype) "function"
                        }
                    }
                }
            } else {
                set error_message \
                    "$name: Unexpected keywords: $alien_keywords"
            }
        }
    }
    set prop_list [ array get props ]
    return [ list $error_message \
    [ gen::create_signature \
    	$type $prop_list $parameters $returns ] ]
}

proc filter_subprograms { components inline access } {
    set result {}
    foreach component $components {
        lassign $component diagram_id name signature body
        lassign $signature type prop_list parameters returns
        array set props $prop_list
        if {(($type == "subprogram") && ($props(inline) == $inline)) && ($props(access) == $access)} {
            lappend result $component
        }
    }
    return $result
}

proc filter_types { components } {
    set result {}
    foreach component $components {
        lassign $component diagram_id name signature body
        lassign $signature type prop_list parameters returns
        array set props $prop_list
        if {$type == "type"} {
            lappend result $component
        }
    }
    return $result
}

proc find_keywords { list keywords } {
    set result {}
    foreach keyword $keywords {
        if {[ contains $list $keyword ]} {
            lappend result $keyword
        }
    }
    return $result
}

proc find_not_belonging { list keywords } {
    set result {}
    foreach item $list {
        if {[ contains $keywords $item ]} {
            
        } else {
            lappend result $item
        }
    }
    return $result
}

proc generate { db gdb filename } {
    set error_message ""
    set prefix [ string cat [ \
    	file dirname $filename ] "/" ]
    set trees [ tab::generate_trees $gdb ]
    foreach tree $trees {
        create_tree $prefix $tree
    }
    set callbacks [ make_callbacks ]
    set diagrams [ $gdb eval { \
    	select diagram_id from diagrams } ]
    foreach diagram_id $diagrams {
        if {[ mwc::is_drakon $diagram_id ]} {
            gen::fix_graph_for_diagram_to \
            	$gdb $callbacks 1 $diagram_id
        }
    }
    set sections { 
      spec_header spec_footer body_header body_footer
    }
    lassign [ gen::scan_file_description $db $sections ] \
      spec_header spec_footer body_header body_footer
    set use_nogoto 1
    set components [ gen::generate_functions_core \
    	$db $gdb $callbacks $use_nogoto 1 ]
    if {[ graph::errors_occured ]} {
        
    } else {
        foreach component $components {
            lassign $component diagram_id name signature body
            lassign $signature type prop_list parameters returns
            array set props $prop_list
            if {$type == "subprogram" \
	&& $props(abstract) \
	&& $body != {{}}} {
                set error_message \
                	"$name: abstract subprogram cannot have body"
            }
        }
        if {$error_message == ""} {
            set spec_filename [ replace_extension $filename "ads" ]
            set body_filename [ replace_extension $filename "adb" ]
            set filenames [ list $spec_filename $body_filename ]
            lassign [ open_files $filenames "w" ] sfile bfile
            catch {
                print_spec $spec_filename $sfile $components \
            	$spec_header $spec_footer
            
                print_body $body_filename $bfile $components \
            	$body_header $body_footer
            } error_message
            close_files [ list $sfile $bfile ]
            if {$error_message == ""} {
                
            } else {
                puts $::errorInfo
                error $error_message
            }
        } else {
            puts $::errorInfo
            error $error_message
        }
    }
}

proc generate_body { gdb diagram_id start_item node_list sorted incoming } {
    return [ list {} ]
}

proc generate_type { gdb diagram_id callbacks } {
    set extract_signature [ \
    	gen::get_callback $callbacks signature ]
    set start_info [ gen::get_start_info $gdb $diagram_id ]
    lassign $start_info \
    	start_icon params_icon name params_text start_item
    set signature [ $extract_signature $params_text $name ]
    lassign $signature errorMessage real_sign
    if {$errorMessage == ""} {
        
    } else {
        gen::report_error $diagram_id {} $errorMessage
    }
    return $name
}

proc generate_types_core { db gdb callbacks } {
    set result {}
    $gdb eval {
    	select diagram_id
    	from diagrams
    	order by name
    } {
    	if { [ mwc::is_drakon $diagram_id ] && \
    	[ gen::has_branches $gdb $diagram_id ] } {
    		lappend result [ generate_type \
    			$gdb $diagram_id $callbacks ]
    	}
    }
    return $result
}

proc make_callbacks { } {
    set callbacks {}
    gen::put_callback callbacks and                 gen_ada::p.and
    gen::put_callback callbacks or                  gen_ada::p.or
    gen::put_callback callbacks not                 gen_ada::p.not
    	
    gen::put_callback callbacks assign              gen_ada::assign
    gen::put_callback callbacks declare             gen_ada::declare
    gen::put_callback callbacks compare             gen_ada::compare
    gen::put_callback callbacks shelf               gen_ada::shelf
    gen::put_callback callbacks comment             gen_ada::comment
    	
    gen::put_callback callbacks break               gen_ada::p.break
    gen::put_callback callbacks pass                gen_ada::pass
    
    gen::put_callback callbacks block_close         gen_ada::block_close
    gen::put_callback callbacks else_start          gen_ada::else_start
    gen::put_callback callbacks while_start         gen_ada::while_start
    	
    gen::put_callback callbacks body                gen_ada::generate_body
    gen::put_callback callbacks signature           gen_ada::extract_signature
    return $callbacks
}

proc make_indent { depth } {
    set indent ""
    set i 0
    while { 1 } {
        if {$i < $depth} {
            
        } else {
            break
        }
        append indent "   "
        incr i
    }
    return $indent
}

proc p.and { left right } {
    return ""
}

proc p.break { } {
    return ""
}

proc p.not { operand } {
    return ""
}

proc p.or { left right } {
    return ""
}

proc pass { } {
    return ""
}

proc print_body { filename fhandle components header footer } {
    put_credits $fhandle
    puts $fhandle $header
    foreach subprogram [ filter_subprograms $components 1 static ] {
        print_subprogram $fhandle $subprogram 0
    }
    foreach subprogram [ filter_subprograms $components 0 static ] {
        print_subprogram $fhandle $subprogram 0
    }
    foreach subprogram [ filter_subprograms $components 0 public ] {
        print_subprogram $fhandle $subprogram 0
    }
    foreach subprogram [ filter_subprograms $components 0 private ] {
        print_subprogram $fhandle $subprogram 0
    }
    puts $fhandle $footer
}

proc print_spec { filename fhandle components header footer } {
    put_credits $fhandle
    puts $fhandle $header
    foreach type [ filter_types $components ] {
        print_type $fhandle $type
    }
    foreach subprogram [ filter_subprograms $components 1 public ] {
        print_subprogram $fhandle $subprogram 0
    }
    foreach subprogram [ filter_subprograms $components 0 public ] {
        print_subprogram $fhandle $subprogram 1
    }
    if {[ llength \
	[ filter_subprograms \
	$components 0 private ] ] == 0} {
        
    } else {
        puts $fhandle ""
        puts $fhandle "private"
        foreach subprogram [ filter_subprograms $components 0 private ] {
            print_subprogram $fhandle $subprogram 1
        }
    }
    puts $fhandle $footer
}

proc print_subprogram { fhandle component in_header } {
    lassign $component diagram_id name signature body
    lassign $signature type prop_list parameters returns
    array set props $prop_list
    if {$props(abstract) && !$in_header} {
        
    } else {
        set static [ expr { $props(access) != "public" } ]
        set print_body [ expr !$in_header ]
        set depth 1
        print_subprogram_kernel \
        $fhandle \
        $depth \
        $static \
        $props(subtype) \
        $props(inline) \
        $props(abstract) \
        $returns \
        $name \
        $parameters \
        $body \
        $print_body
    }
}

proc print_subprogram_kernel { fhandle depth static type inline abstract returns name parameters body print_body } {
    set result {}
    set line ""
    append line "$type "
    append line "$name "
    set param_count [ llength $parameters ]
    if {$param_count == 0} {
        
    } else {
        append line "\("
        lappend result $line
        set i 0
        while { 1 } {
            if {$i < $param_count} {
                
            } else {
                break
            }
            set parameter_info [ lindex $parameters $i ]
            set parameter [ lindex $parameter_info 0 ]
            set line "   $parameter"
            if {$i == $param_count - 1} {
                
            } else {
                append line ";"
            }
            lappend result $line
            incr i
        }
        set line "\)"
    }
    if {$type == "function"} {
        append line " return $returns"
    }
    if {$abstract} {
        append line " is abstract"
        append line ";"
        lappend result $line
    } else {
        if {$print_body} {
            append line " is"
            lappend result $line
            lappend result "begin"
            foreach line $body {
                lappend result "   $line"
            }
            lappend result "end $name;"
        } else {
            append line ";"
            lappend result $line
        }
    }
    set space [ make_indent $depth ]
    foreach line $result {
        puts -nonewline $fhandle $space
        puts $fhandle $line
    }
    puts $fhandle ""
}

proc print_type { fhandle component } {
    lassign $component diagram_id name signature body
    lassign $signature type prop_list parameters returns
    array set props $prop_list
    set depth 1
    set has_body 1
    print_type_kernel \
    $fhandle \
    $depth \
    $props(subtype) \
    $props(abstract) \
    $props(tagged) \
    $name \
    $body \
    $has_body
}

proc print_type_kernel { fhandle depth type abstract tagged name body has_body } {
    set result {}
    set line ""
    append line "$type "
    append line "$name "
    append line "is"
    if {$abstract} {
        append line " abstract"
    }
    if {$tagged} {
        append line " tagged"
    }
    if {$has_body} {
        lappend result $line
        foreach line $body {
            lappend result "   $line"
        }
    } else {
        append line ";"
        lappend result $line
    }
    set space [ make_indent $depth ]
    foreach line $result {
        puts -nonewline $fhandle $space
        puts $fhandle $line
    }
    puts $fhandle ""
}

proc put_credits { fhandle } {
    set version [ version_string ]
    puts $fhandle \
        "-- Autogenerated with DRAKON Editor $version"
}

proc shelf { primary secondary } {
    if {$secondary == "record"} {
        set lines {}
        lappend lines "record"
        foreach line [ split $primary "\n" ] {
            lappend lines "   $line;"
        }
        lappend lines "end record;"
        set result [ join $lines "\n" ]
    } else {
        set result $primary
    }
    return $result
}

proc while_start { } {
    return ""
}

}
