# Custom C generation plugin (no gotos)
# Author: SBP
# Based on c.drn, cpp.drn, cs.drn, c2.tcl
# Thanks to their respective authors!

gen::add_generator "C3" gen_c3::generate

namespace eval gen_c3 {

variable src_file ""

variable c3_keywords {
    _Alignof
    _Generic
    _Static_assert
    alignof
    break
    case
    char
    continue
    default
    do
    double
    else
    enum
    float
    for
    goto
    if
    int
    inline
    long
    public
    return
    returns
    short
    signed
    sizeof
    static_assert
    struct
    switch
    typedef
    typeof
    union
    unsigned
    void
    while
}

variable c3_types {
    _Alignas
    _Atomic
    _Thread_local
    alignas
    auto
    bool
    char
    const
    double
    enum
    extern
    float
    int
    int8_t
    int16_t
    int32_t
    int64_t
    intmax_t
    long
    register
    restrict
    short
    signed
    static
    struct
    thread_local
    union
    unsigned
    uint8_t
    uint16_t
    uint32_t
    uint64_t
    uintmax_t
    void
    volatile
}

# Autogenerated with DRAKON Editor 1.33

proc and { left right } {
    return "\($left\) && \($right\)"
}

proc assign { var value } {
    return "$var = $value;"
}

proc bad_case { switch_var select_icon_number } {
    if {[ string compare -nocase $switch_var "select" ] == 0} {
        return "assert(0 && \"Unexpected condition\");"
    } else {
        return "assert(0 && \"Unexpected $switch_var\");"
    }
}

proc block_close { output depth } {
    upvar 1 $output result
    set line [ gen::make_indent $depth ]
    append line "\}"
    lappend result $line
}

proc commentator { text } {
    return "//" $text
}

proc compare { var value } {
    return "$var == $value"
}

proc declare { type name value } {
    if {$value == ""} {
        return "$type $name;"
    } else {
        return "$type $name = $value;"
    }
}

proc else_start { } {
    return "\} else \{"
}

proc elseif_start { } {
    return "\} else if \("
}

proc extract_return_type { text } {
    set skip [ string length "returns " ]
    set raw [ string range $text $skip end ]
    return [ string trim $raw ]
}

proc generate { db gdb filename } {
    global errorInfo
    variable callbacks
    variable language
    set language "c"
    set callbacks [ make_callbacks ]
    set machines [ sma::extract_many_machines \
     $gdb $callbacks ]
    set sm_header [ gen_cpp::build_sm_header $machines ]
    set sm_body [ gen_cpp::build_sm_body $gdb $machines ]
    gen_cpp::append_sm_names $gdb
    gen_cpp::zap_cleanups $gdb
    tab::generate_tables $gdb $callbacks 0
    set diagrams [ $gdb eval {
    	select diagram_id from diagrams } ]
    foreach diagram_id $diagrams {
        if {[ mwc::is_drakon $diagram_id ]} {
            set append_semicolon 1
            gen::fix_graph_for_diagram \
            $gdb $callbacks $append_semicolon $diagram_id
        }
    }
    if {[ graph::errors_occured ]} {
        return
    }
    set sections { 
      h_header h_footer c_header c_footer class options
      structure globals
    }
    lassign [ gen::scan_file_description $db $sections ] \
      h_header h_footer c_header c_footer class options \
      structure globals
    lassign \
    [gen_cpp::build_globals $globals] \
    g_header g_body
    set functions [ gen::generate_functions $db $gdb  \
    	$callbacks 1 ]
    if {[ graph::errors_occured ]} {
        
    } else {
        set copying 0
        set class_name ""
        set functions [ gen_cpp::update_returns $gdb $functions ]
        lassign [ gen_cpp::sort_functions $functions $language $class_name ] \
        free_funs \
        ctrs dtrs methods signals slots
        set h_filename [ replace_extension $filename "h" ]
        set c_filename [ replace_extension $filename $language ]
        set filenames [ list $h_filename $c_filename ]
        lassign [ open_files $filenames "w" ] hfile cfile
        catch {
            print_header $h_filename $hfile $free_funs \
            $h_header $h_footer \
            $language $sm_header $g_header
            
            gen_cpp::print_cpp $h_filename $cfile \
            $free_funs $ctrs $dtrs $methods $slots \
            $c_header $c_footer $class_name \
            $language $sm_body $g_body
        } error_message
        close_files [ list $hfile $cfile ]
        if {$error_message == ""} {
            
        } else {
            puts $::errorInfo
            error $error_message
        }
    }
}

proc generate_body { gdb diagram_id start_item node_list items incoming } {
    set callbacks [ make_callbacks ]
    generate_body_goto \
    $gdb $diagram_id $start_item $node_list $items $incoming \
    $callbacks
}

proc highlight { tokens } {
    variable c3_keywords
    variable c3_types
    return [ highlight_generic $c3_keywords $c3_types $tokens ]
}

proc highlight_generic { keywords kw_types tokens } {
    set result {}
    set state "idle"
    foreach token $tokens {
        lassign $token type text
        if {$state == "idle"} {
            set state \
            [ idle_default $keywords $kw_types result $type $text ]
        } else {
            if {$state == "string"} {
                lappend result $colors::syntax_string
                if {$text == "\""} {
                    set state "idle"
                } else {
                    if {$text == "\\"} {
                        set state "escaping"
                    } else {
                        if {$text == "\n"} {
                            set state "idle"
                        }
                    }
                }
            } else {
                if {$state == "escaping"} {
                    lappend result $colors::syntax_string
                    if {$text == "\n"} {
                        set state "idle"
                    } else {
                        set state "string"
                    }
                } else {
                    if {$state == "comment start"} {
                        if {$text == "*"} {
                            set state "comment"
                            lappend result $colors::syntax_comment \
                            	$colors::syntax_comment
                        } else {
                            if {$text == "/"} {
                                set state "comment line"
                                lappend result $colors::syntax_comment \
                                	$colors::syntax_comment
                            } else {
                                lappend result $colors::syntax_operator
                                set state \
                                [ idle_default $keywords $kw_types result $type $text ]
                            }
                        }
                    } else {
                        if {$state == "comment"} {
                            lappend result $colors::syntax_comment
                            if {$text == "*"} {
                                set state "comment end"
                            }
                        } else {
                            if {$state == "comment end"} {
                                lappend result $colors::syntax_comment
                                if {$text == "/"} {
                                    set state "idle"
                                }
                            } else {
                                if {$state == "comment line"} {
                                    lappend result $colors::syntax_comment
                                    if {$text == "\n"} {
                                        set state "idle"
                                    }
                                } else {
                                    if {$state == "char"} {
                                        lappend result $colors::syntax_string
                                        if {$text == "'"} {
                                            set state "idle"
                                        } else {
                                            if {$text == "\\"} {
                                                set state "char escaping"
                                            } else {
                                                if {$text == "\n"} {
                                                    set state "idle"
                                                }
                                            }
                                        }
                                    } else {
                                        if {$state == "char escaping"} {
                                            lappend result \
                                              $colors::syntax_string
                                            if {$text == "\n"} {
                                                set state "idle"
                                            } else {
                                                set state "char"
                                            }
                                        } else {
                                            if {$state == "verbatim start"} {
                                                if {$text == "\""} {
                                                    lappend result $colors::syntax_string \
                                                    	$colors::syntax_string
                                                    set state "verbatim"
                                                } else {
                                                    lappend result $colors::syntax_operator
                                                    set state \
                                                    [ idle_default $keywords $kw_types result $type $text ]
                                                }
                                            } else {
                                                if {$state == "verbatim"} {
                                                    lappend result $colors::syntax_string
                                                    if {$text == "\""} {
                                                        set state "verbatim end"
                                                    }
                                                } else {
                                                    if {$state == "verbatim end"} {
                                                        
                                                    } else {
                                                        error "Unexpected switch value: $state"
                                                    }
                                                    if {$text == "\""} {
                                                        lappend result $colors::syntax_string
                                                        set state "verbatim"
                                                    } else {
                                                        set state \
                                                        [ idle_default $keywords $kw_types result $type $text ]
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    if {($state == "comment start") || ($state == "verbatim start")} {
        lappend result $colors::syntax_operator
    }
    return $result
}

proc idle_default { keywords kw_types result_name type text } {
    upvar 1 $result_name result
    if {$text == "\""} {
        lappend result $colors::syntax_string
        set state "string"
    } else {
        if {$text == "'"} {
            lappend result $colors::syntax_string
            set state "char"
        } else {
            if {$text == "/"} {
                set state "comment start"
            } else {
                if {$text == "@"} {
                    set state "verbatim start"
                } else {
                    lappend result [standard_color $keywords $kw_types $type $text]
                    set state "idle"
                }
            }
        }
    }
    return $state
}

proc if_end { } {
    return "\) \{"
}

proc if_start { } {
    return "if \("
}

proc make_callbacks { } {
    set callbacks {}
    gen::put_callback callbacks assign		gen_c3::assign
    gen::put_callback callbacks compare		gen_c3::compare
    gen::put_callback callbacks compare2	gen_c3::compare
    gen::put_callback callbacks bad_case	gen_c3::bad_case
    
    gen::put_callback callbacks body		gen_c3::generate_body
    gen::put_callback callbacks signature	gen_cpp::extract_signature
    gen::put_callback callbacks and		gen_c3::and
    gen::put_callback callbacks or		gen_c3::or
    gen::put_callback callbacks not		gen_c3::not
    gen::put_callback callbacks declare		gen_c3::declare
    
    gen::put_callback callbacks if_start	gen_c3::if_start
    gen::put_callback callbacks if_end		gen_c3::if_end
    gen::put_callback callbacks else_start	gen_c3::else_start
    gen::put_callback callbacks elseif_start	gen_c3::elseif_start
    gen::put_callback callbacks block_close	gen_c3::block_close
    gen::put_callback callbacks return_none	gen_c3::return_none
    gen::put_callback callbacks shelf		gen_c3::shelf
    
    gen::put_callback callbacks while_start	gen_c3::while_start
    gen::put_callback callbacks pass		gen_c3::pass
    gen::put_callback callbacks comment		gen_c3::commentator
    gen::put_callback callbacks break		"break;"
    return $callbacks
}

proc not { operand } {
    return "!\($operand\)"
}

proc or { left right } {
    return "\($left\) || \($right\)"
}

proc pass { } {
    return ""
}

proc print_header { filename fhandle functions header footer language structure globals } {
    gen_cpp::put_credits $fhandle
    set guard [ gen_c::guard_name $filename ]
    puts $fhandle "#ifndef $guard"
    puts $fhandle "#define $guard"
    puts $fhandle ""
    puts $fhandle $header
    variable src_file
    set module_name [ \
    gen_cpp::take_module_name $src_file ]
    init_current_file $fhandle
    gen_c_t::generate_h $module_name
    puts $fhandle ""
    puts $fhandle $structure
    puts $fhandle ""
    puts $fhandle $globals
    foreach function [ gen_cpp::filter_functions $functions 0 public ] {
        lassign $function diagram_id name signature body
        if {$name == "main"} {
            
        } else {
            gen_cpp::print_function \
            $fhandle $function 1 "" $language
        }
    }
    foreach function [ gen_cpp::filter_functions $functions 1 public ] {
        gen_cpp::print_function \
        $fhandle $function 1 "" $language
    }
    foreach function [ gen_cpp::filter_functions $functions 1 public ] {
        gen_cpp::print_function \
        $fhandle $function 0 "" $language
    }
    puts $fhandle $footer
    puts $fhandle "#endif"
    puts $fhandle ""
}

proc return_none { } {
    return "return;"
}

proc shelf { primary secondary } {
    return "$secondary = $primary;"
}

proc standard_color { keywords kw_types type text } {
    if {$type == "op"} {
        return $colors::syntax_operator
    } else {
        if {$type == "number"} {
            return $colors::syntax_number
        } else {
            if {$type == "token"} {
                if {[contains $kw_types $text]} {
                    return $colors::syntax_type
                } else {
                    if {[contains $keywords $text]} {
                        return $colors::syntax_keyword
                    } else {
                        return $colors::syntax_identifier
                    }
                }
            } else {
                return $colors::syntax_identifier
            }
        }
    }
}

proc while_start { } {
    return "while(1) \{"
}

}
